@startuml
class MouseFlightController {
    - useFixed : bool = true
    - camSmoothSpeed : float = 5f
    - mouseSensitivity : float = 3f
    - aimDistance : float = 500f
    - showDebugInfo : bool = false
    - isMouseAimFrozen : bool = false
    - Start() : void
    - Update() : void
    - FixedUpdate() : void
    - RotateRig() : void
    - GetFrozenMouseAimPos() : Vector3
    - UpdateCameraPos() : void
    - Damp(a:Quaternion, b:Quaternion, lambda:float, dt:float) : Quaternion
    - OnDrawGizmos() : void
}
MonoBehaviour <|-- MouseFlightController
MouseFlightController o-> "aircraft" Transform
MouseFlightController o-> "mouseAim" Transform
MouseFlightController o-> "cameraRig" Transform
MouseFlightController o-> "cam" Transform
MouseFlightController o-> "frozenDirection" Vector3
MouseFlightController --> "BoresightPos" Vector3
MouseFlightController --> "MouseAimPos" Vector3
@enduml
