@startuml
class Shooter {
    - timeBetweenBullets : float = 1f
    - timeBetweenRockets : float = 5f
    - radarDistance : float = 10f
    - timeToLockTarget : float = 5f
    - lockDuration : float = 5f
    - timePastSinceLastBullet : float = 0f
    - timePastSinceLastRocket : float = 0f
    - timeUntilLock : float
    - timeUntilUnlock : float
    - Start() : void
    Update() : void
    - accquireTarget() : void
}
MonoBehaviour <|-- Shooter
Shooter --> "plane" GameObject
Shooter --> "radarPoint" GameObject
Shooter --> "currentLock" GameObject
Shooter --> "lastLock" GameObject
Shooter --> "currentTarget" GameObject
Shooter --> "planeRb" Rigidbody
Shooter --> "playerManager" PlayerManager
@enduml
