@startuml
class Plane {
    + thrust : float = 100f
    + thrustMult : float = 1000f
    + turnMult : float = 1000f
    + sensitivity : float = 5f
    + aggressiveTurnAngle : float = 10f
    - pitch : float = 0f
    - yaw : float = 0f
    - roll : float = 0f
    + Pitch : float <<set>> <<get>>
    + Yaw : float <<set>> <<get>>
    + Roll : float <<set>> <<get>>
    - rollOverride : bool = false
    - pitchOverride : bool = false
    - Awake() : void
    - Update() : void
    - RunAutopilot(flyTarget:Vector3, yaw:float, pitch:float, roll:float) : void
    - FixedUpdate() : void
}
MonoBehaviour <|-- Plane
Plane o-> "controller" MouseFlightController
Plane o-> "turnTorque" Vector3
Plane --> "rigid" Rigidbody
@enduml
