@startuml
class PlayerControllerScript {
    + isOwned : bool
    - xRot : float = 0
    - currentBulletDelay : float
    - crouch : bool
    - shooting : bool
    - bulletDelay : float
    - speed : float
    - sensitivity : float
    - Start() : void
    - Update() : void
    - updatePlayer() : void
    - movePlayer(moveInput:Vector3) : void
    - movePlayerCamera(lookInput:Vector2) : void
    - jump() : void
    - shoot() : void
    - createBullet(type:String) : void
    - sneak(sneak:bool) : void
    + setName(name:string) : void
    + disableNameTag() : void
    + rotateNameTowards(objectToLookAt:GameObject) : void
    - OnDestroy() : void
}
MonoBehaviour <|-- PlayerControllerScript
PlayerControllerScript --> "lookInput" Vector2
PlayerControllerScript --> "moveInput" Vector3
PlayerControllerScript o-> "defaultPositionRange" Vector2
PlayerControllerScript --> "controls" Controls
PlayerControllerScript --> "playerCamera" Camera
PlayerControllerScript --> "playerBody" Rigidbody
PlayerControllerScript --> "nameDisplay" TMP_Text
PlayerControllerScript --> "nameTagCanvas" Canvas
PlayerControllerScript --> "pointBlank" GameObject
@enduml
