@startuml
class Benchmark01_UGUI {
    + BenchmarkType : int = 0
    - <<const>> label01 : string = "The <#0050FF>count is: </color>"
    - <<const>> label02 : string = "The <color=#0050FF>count is: </color>"
    Start() : IEnumerator
}
MonoBehaviour <|-- Benchmark01_UGUI
Benchmark01_UGUI --> "canvas" Canvas
Benchmark01_UGUI --> "TMProFont" TMP_FontAsset
Benchmark01_UGUI --> "TextMeshFont" Font
Benchmark01_UGUI --> "m_textMeshPro" TextMeshProUGUI
Benchmark01_UGUI --> "m_textMesh" Text
Benchmark01_UGUI --> "m_material01" Material
Benchmark01_UGUI --> "m_material02" Material
@enduml
