@startuml
class ExternalLinks {
    + <<const>> RemoteVersionURL : string = "https://raw.githubusercontent.com/VeriorPies/ParrelSync/master/VERSION.txt"
    + <<const>> Releases : string = "https://github.com/VeriorPies/ParrelSync/releases"
    + <<const>> CustomArgumentHelpLink : string = "https://github.com/VeriorPies/ParrelSync/wiki/Argument"
    + <<const>> GitHubHome : string = "https://github.com/VeriorPies/ParrelSync/"
    + <<const>> GitHubIssue : string = "https://github.com/VeriorPies/ParrelSync/issues"
    + <<const>> FAQ : string = "https://github.com/VeriorPies/ParrelSync/wiki/Troubleshooting-&-FAQs"
}
@enduml
