@startuml
class BoolPreference {
    + key : string <<get>>
    + defaultValue : bool <<get>>
    + BoolPreference(key:string, defaultValue:bool)
    - valueCache : bool? = null
    + Value : bool <<get>> <<set>>
    + ClearValue() : void
}
class Preferences {
    - {static} InitWindow() : void
    - OnGUI() : void
}
EditorWindow <|-- Preferences
Preferences o-> "AssetModPref" BoolPreference
Preferences o-> "AlsoCheckUnityLockFileStaPref" BoolPreference
@enduml
