@startuml
class UDPClient {
    + thisPort : int
    - PORT : int
    - IP : string
    + UDPClient(ip:string, serverPort:int, localPort:int)
    + connect() : void
    sendMessageOnUDP(message:string) : void
    sendCallStack() : void
    receiveMessageOnUDP() : void
    - OnApplicationQuit() : void
}
class "List`1"<T> {
}
UDPClient --> "udpCallStack<string>" "List`1"
UDPClient --> "updClient" UdpClient
UDPClient --> "remoteEndPoint" IPEndPoint
UDPClient --> "sender" Thread
UDPClient --> "receiver" Thread
@enduml
