@startuml
class Projectile {
    + damage : int
    + projectileSpeed : float
    + despawnTime : float
    + timeUntilProjectileGetsLethal : float
    + shooter : string
    + OnStart() : void
    + OnUpdate() : void
    + updateCollidersOfGameObject(colliderGameObject:GameObject, newState:bool) : void
    + updateColorsOfGameObject(rendererGameObject:GameObject, newColor:Color) : void
    + listToVector3(input:List<float>) : Vector3
    + OnCollisionEnter(other:Collision) : void
    + destroyProjectile() : void
}
MonoBehaviour <|-- Projectile
Projectile --> "angleToFireProjectile" Vector3
Projectile --> "originalVelocity" Vector3
Projectile --> "projectileType" Enum
Projectile --> "projectileRigidbody" Rigidbody
Projectile --> "ColliderObject" GameObject
@enduml
