@startuml
class ShaderPropAnimator {
    + m_frame : float
    Awake() : void
    Start() : void
    AnimateProperties() : IEnumerator
}
MonoBehaviour <|-- ShaderPropAnimator
ShaderPropAnimator --> "m_Renderer" Renderer
ShaderPropAnimator --> "m_Material" Material
ShaderPropAnimator --> "GlowCurve" AnimationCurve
@enduml
