@startuml
class SkewTextExample {
    + CurveScale : float = 1.0f
    + ShearAmount : float = 1.0f
    Awake() : void
    Start() : void
    - CopyAnimationCurve(curve:AnimationCurve) : AnimationCurve
    WarpText() : IEnumerator
}
MonoBehaviour <|-- SkewTextExample
SkewTextExample --> "m_TextComponent" TMP_Text
SkewTextExample o-> "VertexCurve" AnimationCurve
@enduml
