@startuml
class Benchmark02 {
    + SpawnType : int = 0
    + NumberOfNPC : int = 12
    + IsTextObjectScaleStatic : bool
    Start() : void
}
MonoBehaviour <|-- Benchmark02
Benchmark02 --> "floatingText_Script" TextMeshProFloatingText
@enduml
