@startuml
class ChatController {
    OnEnable() : void
    OnDisable() : void
    AddToChatOutput(newText:string) : void
}
MonoBehaviour <|-- ChatController
ChatController --> "ChatInputField" TMP_InputField
ChatController --> "ChatDisplayOutput" TMP_Text
ChatController --> "ChatScrollbar" Scrollbar
@enduml
