@startuml
class WarpTextExample {
    + AngleMultiplier : float = 1.0f
    + SpeedMultiplier : float = 1.0f
    + CurveScale : float = 1.0f
    Awake() : void
    Start() : void
    - CopyAnimationCurve(curve:AnimationCurve) : AnimationCurve
    WarpText() : IEnumerator
}
MonoBehaviour <|-- WarpTextExample
WarpTextExample --> "m_TextComponent" TMP_Text
WarpTextExample o-> "VertexCurve" AnimationCurve
@enduml
