@startuml
class Hud {
    - Awake() : void
    - Update() : void
    - UpdateGraphics(controller:MouseFlightController) : void
    + SetReferenceMouseFlight(controller:MouseFlightController) : void
}
MonoBehaviour <|-- Hud
Hud o-> "mouseFlight" MouseFlightController
Hud o-> "boresight" RectTransform
Hud o-> "mousePos" RectTransform
Hud o-> "healthDisplay" TMP_Text
Hud o-> "lockInfoDisplay" TMP_Text
Hud o-> "playerHealth" PlayerHealth
Hud o-> "playerCam" Camera
@enduml
