@startuml
class PlayerHealth {
    + myId : string
    - currentHealth : int
    - Update() : void
    + takeDamage(damage:int) : void
    + setHealth(newHealth:int) : void
    + getHealth() : int
}
MonoBehaviour <|-- PlayerHealth
@enduml
