@startuml
class NetworkedVariables <<static>> {
    + {static} inGame : bool
    + {static} isDead : bool
    + {static} worldIndex : int
    + {static} playerId : string
    + {static} roomId : string
    + {static} errorMessage : string
}
class "Dictionary`2"<T1,T2> {
}
class "List`1"<T> {
}
NetworkedVariables --> "ownedPlayerTransform" Transform
NetworkedVariables o-> "allConnectedPlayerTransforms<string,List<List<float>>>" "Dictionary`2"
NetworkedVariables o-> "playerNames<string,string>" "Dictionary`2"
NetworkedVariables o-> "planeTypes<string,PlaneTypes>" "Dictionary`2"
NetworkedVariables o-> "playerHealths<string,int>" "Dictionary`2"
NetworkedVariables o-> "scenceToLoad<int>" "List`1"
NetworkedVariables o-> "disconnectedPlayerIds<string>" "List`1"
NetworkedVariables o-> "targetLockInfo<Dictionary<string, string>>" "List`1"
NetworkedVariables o-> "deadPlayers<Dictionary<string, string>>" "List`1"
NetworkedVariables o-> "playersToRejoin<Dictionary<string, string>>" "List`1"
NetworkedVariables o-> "currentGameMode" GameModeTypes
@enduml
