@startuml
!include .\\.\ParrelSync\Examples\CustomArgumentExample.puml
!include .\\.\Scripts\Controlls\Controls.puml
!include .\\.\Scripts\Networking\JsonParser.puml
!include .\\.\Scripts\Networking\NetworkedVariables.puml
!include .\\.\Scripts\Networking\PlayerManager.puml
!include .\\.\Scripts\Networking\ProjectileManager.puml
!include .\\.\Scripts\Networking\TCPClient.puml
!include .\\.\Scripts\Networking\UDPClient.puml
!include .\\.\Scripts\Player\Hud.puml
!include .\\.\Scripts\Player\MouseFlightController.puml
!include .\\.\Scripts\Player\Plane.puml
!include .\\.\Scripts\Player\PlayerCollisionManager.puml
!include .\\.\Scripts\Player\PlayerControllerScript.puml
!include .\\.\Scripts\Player\PlayerDummyScript.puml
!include .\\.\Scripts\Player\PlayerHealth.puml
!include .\\.\Scripts\Player\PlayerNetworking.puml
!include .\\.\Scripts\Player\Shooter.puml
!include .\\.\Scripts\Projectiles\Bullet.puml
!include .\\.\Scripts\Projectiles\Projectile.puml
!include .\\.\Scripts\Projectiles\Rocket.puml
!include .\\.\Scripts\Scene\SceneDirector.puml
!include .\\.\Scripts\Ui\DeathUIManager.puml
!include .\\.\Scripts\Ui\JoinUIManager.puml
!include .\\.\Scripts\Ui\PlaneImageController.puml
!include .\\.\Scripts\Ui\SelectionUIManager.puml
!include .\\.\Scripts\Ui\WorldUIManager.puml
!include .\\.\Scripts\Utility\GameModeManager.puml
!include .\\.\Scripts\Utility\PrefabOrganizer.puml
!include .\\.\ParrelSync\ParrelSync\Editor\ClonesManager.puml
!include .\\.\ParrelSync\ParrelSync\Editor\ClonesManagerWindow.puml
!include .\\.\ParrelSync\ParrelSync\Editor\ExternalLinks.puml
!include .\\.\ParrelSync\ParrelSync\Editor\FileUtilities.puml
!include .\\.\ParrelSync\ParrelSync\Editor\Preferences.puml
!include .\\.\ParrelSync\ParrelSync\Editor\Project.puml
!include .\\.\ParrelSync\ParrelSync\Editor\UpdateChecker.puml
!include .\\.\ParrelSync\ParrelSync\Editor\ValidateCopiedFoldersIntegrity.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\Benchmark01.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\Benchmark01_UGUI.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\Benchmark02.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\Benchmark03.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\Benchmark04.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\CameraController.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\ChatController.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\DropdownSample.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\EnvMapAnimator.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\ObjectSpin.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\ShaderPropAnimator.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\SimpleScript.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\SkewTextExample.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TeleType.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TextConsoleSimulator.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TextMeshProFloatingText.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TextMeshSpawner.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMPro_InstructionOverlay.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_DigitValidator.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_ExampleScript_01.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_FrameRateCounter.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_PhoneNumberValidator.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_TextEventCheck.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_TextEventHandler.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_TextInfoDebugTool.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_TextSelector_A.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_TextSelector_B.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\TMP_UiFrameRateCounter.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\VertexColorCycler.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\VertexJitter.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\VertexShakeA.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\VertexShakeB.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\VertexZoom.puml
!include .\\.\TextMesh Pro\Examples & Extras\Scripts\WarpTextExample.puml
!include .\\.\ParrelSync\ParrelSync\Editor\AssetModBlock\EditorQuit.puml
!include .\\.\ParrelSync\ParrelSync\Editor\AssetModBlock\ParrelSyncAssetModificationProcessor.puml
!include .\\.\ParrelSync\ParrelSync\Editor\NonCore\AskFeedbackDialog.puml
!include .\\.\ParrelSync\ParrelSync\Editor\NonCore\OtherMenuItem.puml
@enduml
