@startuml
class WorldUIManager {
    - Start() : void
    - Update() : void
    + disconnect() : void
    + continueGame() : void
}
MonoBehaviour <|-- WorldUIManager
WorldUIManager --> "roomIdDisplay" TMP_Text
WorldUIManager --> "nameDisplay" TMP_Text
WorldUIManager --> "pauseMenu" GameObject
@enduml
